#import archlinux-base-devel
FROM base/devel:latest

#install dependencies for kernel building
RUN pacman -Sy git bc imagemagick xmlto python-sphinx graphviz --noconfirm

#change number of processors here
RUN sed -i -e 's/.*MAKEFLAGS=.*/MAKEFLAGS="j16"/' /etc/makepkg.conf

#add a user other than root and use it to build the kernel;
#Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
RUN useradd nonroot -m -d /home/nonroot
USER nonroot
WORKDIR /home/nonroot

# copy the kernel fom AUR git and build it
RUN git clone https://aur.archlinux.org/linux-cx2072x.git
WORKDIR linux-cx2072x
RUN makepkg

#make a direcotry where we store the prebuild binaries, since docker doesn't support running "docker cp linux*xz"
RUN mkdir /home/nonroot/package
RUN mv *.xz /home/nonroot/package
